version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.4.0
    volumes:
      - ./volumes/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/data/:/prometheus
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9090"
    ports:
      - "9090:9090"